name: lesfemmes.no
favicon: null
layout_spectrum: 0.003123435890302062
typography_spectrum: 0.013932105153799057
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefdfb'
    - '#d6bbaa'
    - '#a18377'
    - '#776154'
    - '#4a3d35'
  brandStrength: 0.5670487978495657
  lightness: 0.6558869534637779
  saturation: 0.12258567335084081
  rhythmicContrast: 0.9748929487541318
purpose: []
